/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.24
 * Generated at: 2015-08-18 08:47:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class sns_005flogout_005fmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1439529924450L));
    _jspx_dependants.put("jar:file:/C:/kosaswcourse/workspace-jspex/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/mysns/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t\t<title>Swim!</title>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 스타일 시트 관련 링크  -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/styles.css\" type=\"text/css\" media=\"screen\" /> <!-- 본문의 메인 디자인을 위한 스타일시트 링크 -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css\" /> <!-- jQuery-UI를 사용하기 위한 스타일시트 링크 -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- jquery와 jquery-ui 사용을 위한 자바스크립트파일 링크 -->\r\n");
      out.write("\t\t<script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write("\t\t<script src=\"http://code.jquery.com/ui/1.10.3/jquery-ui.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- accordion 컴포넌트의 이벤트 동작을 위한 jquery구문 -->\r\n");
      out.write("\t\t<!-- 게시글의 제목을 클릭했을 때 본문이 보였다 숨겨졌다 함 -->\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\t$(function() {\r\n");
      out.write("\t\t\t\t$(\"#accordion\").accordion({\r\n");
      out.write("\t\t\t\theightStyle : \"content\",\r\n");
      out.write("\t\t\t\tactive : parseInt(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${curmsg == null ? 0:curmsg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\")\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\tfunction newuser() {\r\n");
      out.write("\t\t\t\twindow.open(\r\n");
      out.write("\t\t\t\t\t\t\"new_user.jsp\",\r\n");
      out.write("\t\t\t\t\t\t\"newuser\",\r\n");
      out.write("\t\t\t\t\t\t\"titlebar=no, location=no, scrollbars=no, resizeable=no, menubar=no, toolbar=no, width=500, height=300\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(document).ready(function(){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar timer=setInterval(function(){\t\r\n");
      out.write("\t\t\t\t\tvar now=new Date();\r\n");
      out.write("\t\t\t\t\tvar hr=now.getHours();\r\n");
      out.write("\t\t\t\t\tvar min=now.getMinutes();\r\n");
      out.write("\t\t\t\t\tvar sec=now.getSeconds();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(hr>=10){\r\n");
      out.write("\t\t\t\t\t\thNum=hr;\t\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\thNum=\"0\"+hr;\r\n");
      out.write("\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(min>=10){\r\n");
      out.write("\t\t\t\t\t\tmNum=min;\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tmNum=\"0\"+min;\r\n");
      out.write("\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(sec>=10){\r\n");
      out.write("\t\t\t\t\t\tsNum=sec;\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tsNum=\"0\"+sec;\r\n");
      out.write("\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"p span\").eq(0).text(hNum);\r\n");
      out.write("\t\t\t\t\t$(\"p span\").eq(1).text(mNum);\r\n");
      out.write("\t\t\t\t\t$(\"p span\").eq(2).text(sNum);\r\n");
      out.write("\t\t\t\t}, 1000)\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"section\").on(\"mousemove\",function(e){\r\n");
      out.write("\t\t\t\t\tvar posX=e.pageX;\r\n");
      out.write("\t\t\t\t\tvar posY=e.pageY;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\".p21\").css({\"right\":-180-(posX/30), \"bottom\":-480-(posY/30)});\r\n");
      out.write("\t\t\t\t\t$(\".p22\").css({\"right\":130+(posX/50), \"bottom\":-40+(posY/50)});\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t</head>\r\n");
      out.write("\t\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div id=\"wrap\">\r\n");
      out.write("\t\t<section>\r\n");
      out.write("\t\t\t<img class=\"p21\" src=\"img/obj21.png\">\r\n");
      out.write("\t\t\t<img class=\"p22\" src=\"img/obj22.png\">\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 주 메뉴 -->\r\n");
      out.write("\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-home fa-1g\"></i>&nbsp; Home</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"sns_login.jsp\"><i class=\"fa fa-user fa-1g\"></i>&nbsp; Logout</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"javascript:newuser()\"><i class=\"fa fa-user-plus fa-1g\"></i>&nbsp; Sign Up</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"sns_control.jsp?action=getall\"><i class=\"fa fa-table fa-1g\"></i>&nbsp; Board</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<!-- sns -->\r\n");
      out.write("\t\t\t<ul id=\"sns\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><img src=\"img/facebook_32.png\"></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><img src=\"img/twitter_32.png\"></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><img src=\"img/youtube_32.png\"></a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 텍스트박스 -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<h1>Let's Swimming!</h1>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 시계 -->\r\n");
      out.write("\t\t\t<p id=\"side\">\t\r\n");
      out.write("\t\t\t\t<span>00</span> : <span>00</span> : <span>00</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
