/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.24
 * Generated at: 2015-08-29 08:36:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\t<html>\r\n");
      out.write("\t\t<head>\r\n");
      out.write("\t\t\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t\t\t<title>JspProgramming</title>\r\n");
      out.write("\t\t\t<style type=\"text/css\">\r\n");
      out.write("\t\t\t\t*{\r\n");
      out.write("\t\t\t\t\tmargin:0px;\r\n");
      out.write("\t\t\t\t\tpadding:0px;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tbody{\r\n");
      out.write("\t\t\t\t\twidth:800px;\t\t\t\t\r\n");
      out.write("\t\t\t\t\tmargin:0 auto;\r\n");
      out.write("\t\t\t\t\tbackground-color:black;\r\n");
      out.write("\t\t\t\t\tbackground-attachment:fixed;\r\n");
      out.write("\t\t\t\t\tdisplay:flex;\r\n");
      out.write("\t\t\t\t\tflex-direction: column;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t#page-wrapper{\r\n");
      out.write("\t\t\t\t\tbackground-color:white;\r\n");
      out.write("\t\t\t\t\tmargin: 40px 0px;\r\n");
      out.write("\t\t\t\t\tpadding: 10px 20px;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t header{\r\n");
      out.write("\t\t\t\t\tmargin-bottom: 10px;\r\n");
      out.write("\t\t\t\t\ttext-shadow: 5px 3px 7px rgba(64,64,0,0.5);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tnav{\r\n");
      out.write("\t\t\t\t\tbackground-color:orange;\r\n");
      out.write("\t\t\t\t\tborder-top:1px solid #c8c8c8;\r\n");
      out.write("\t\t\t\t\tborder-bottom:1px solid #c8c8c8;\r\n");
      out.write("\t\t\t\t\tdisplay: flex;\r\n");
      out.write("\t\t\t\t\tflex-direction: row;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t.menu{\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tmargin: 5px;\r\n");
      out.write("\t\t\t\t\twidth: 70px;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t#content{\r\n");
      out.write("\t\t\t\t\tdisplay:flex;\r\n");
      out.write("\t\t\t\t\theight:400px;\r\n");
      out.write("\t\t\t\t\tflex-direction:row;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t#category{\r\n");
      out.write("\t\t\t\t\theight: 100%;\r\n");
      out.write("\t\t\t\t\toverflow-y: scroll;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t.chapter{\r\n");
      out.write("\t\t\t\t\ttext-align: center;\r\n");
      out.write("\t\t\t\t\tmargin: 4px;\r\n");
      out.write("\t\t\t\t\tfont-style: italic;\r\n");
      out.write("\t\t\t\t\tfont-weight: bold;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t#category > a{\r\n");
      out.write("\t\t\t\t\tdisplay: block;\r\n");
      out.write("\t\t\t\t\tborder:0px;\r\n");
      out.write("\t\t\t\t\tborder-radius: 20px;\r\n");
      out.write("\t\t\t\t\ttext-align: center;\r\n");
      out.write("\t\t\t\t\tline-height: 30px;\r\n");
      out.write("\t\t\t\t\ttext-decoration: none;\r\n");
      out.write("\t\t\t\t\tcolor: #FFFFFF;\r\n");
      out.write("\t\t\t\t\tmargin: 2px;\r\n");
      out.write("\t\t\t\t\tbackground-color: orange;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t#category a:nth-child(2n-1){\r\n");
      out.write("\t\t\t\t\tbackground-color: gray;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t#category >a:hover{\r\n");
      out.write("\t\t\t\t\tbackground-color: red;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\taside{\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\theight:400px;\r\n");
      out.write("\t\t\t\t\twidth: 250px;\r\n");
      out.write("\t\t\t\t\tborder-right:1px solid #c8c8c8;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tsection{\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\theight:400px;\r\n");
      out.write("\t\t\t\t\twidth: 500px;\r\n");
      out.write("\t\t\t\t\tflex: 1;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tiframe{\r\n");
      out.write("\t\t\t\t\tborder : 0px solid black;\r\n");
      out.write("\t\t\t\t\tbackground-color: rgba(160,160,0,0.1);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tfooter{\r\n");
      out.write("\t\t\t\t\theight: 50px;\r\n");
      out.write("\t\t\t\t\tborder-top:1px solid #c8c8c8;\r\n");
      out.write("\t\t\t\t} \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</style>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</head>\r\n");
      out.write("\t\t<body>\r\n");
      out.write("\t\t\t<div id= \"page-wrapper\">\r\n");
      out.write("\t\t\t<header>\r\n");
      out.write("\t\t\t\t<h1>JspProgramming</h1>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</header>\r\n");
      out.write("\t\t\t<nav>\r\n");
      out.write("\t\t\t\t<div class=\"menu\">Menu1</div>\r\n");
      out.write("\t\t\t\t<div class=\"menu\">Menu2</div>\r\n");
      out.write("\t\t\t\t<div class=\"menu\">Menu3</div>\r\n");
      out.write("\t\t\t\t<div class=\"menu\">Menu4</div>\r\n");
      out.write("\t\t\t\t<div class=\"menu\">Menu5</div>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t\t<aside>\r\n");
      out.write("\t\t\t\t\t<div id=\"category\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"chapter\">[Ch05: JSP 기초 문법]</p>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"ch05/comment.jsp\" target=\"iframe\">주석</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"ch05/directives/index.jsp\" target=\"iframe\">지시어</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"ch05/action/index.jsp\" target=\"iframe\">표준액션</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"ch05/dec_express/scriptlet1.jsp\" target=\"iframe\">스크립트릿1</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"ch05/dec_express/scriptlet2.jsp\" target=\"iframe\">스크립트릿2</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"ch05/dec_express/calc3.jsp\" target=\"iframe\">선언문</a>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<p class=\"chapter\">[Ch06: JSP 내장 객체]</p>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"ch06/builtin_object.jsp\" target=\"iframe\">JSP 내장 객체 개요</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"ch06/request/index.jsp\" target=\"iframe\">request</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"ch06/response/index.jsp\" target=\"iframe\">response</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"ch06/cookie/index.jsp\" target=\"iframe\">cookie</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"ch06/session/index.jsp\" target=\"iframe\">session</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"ch06/application/index.jsp\" target=\"iframe\">application</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"ch06/bascket/login.jsp\" target=\"iframe\">장바구니-세션편</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"ch06/twitter/twitter_login.jsp\" target=\"iframe\">트위터</a>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<p class=\"chapter\">[Ch07: JSP 자바 빈즈]</p>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"ch07/dto.jsp\" target=\"iframe\">DTO 이용 방법</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"ch07/dto_auto_setting.jsp\" target=\"iframe\">DTO 값 저장</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"ch07/bean_scope.jsp\" target=\"iframe\">빈의 사용 범위</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"ch07/database_form.jsp\" target=\"iframe\">데이타베이스 연동</a>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<p class=\"chapter\">[ch10: 포현 언어]</p>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<p class=\"chapter\">[ch11: JSTL]</p>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"ch11/forEach.jsp\" target=\"iframe\">&lt;c:forEach&gt;</a>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<p class=\"chapter\">[실습1: 게시판]</p>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"exam01/list.jsp\" target=\"iframe\">게시판 목록</a>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<p class=\"chapter\">[실습2: 게시판]</p>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"exam/list1.jsp\" target=\"iframe\">상품 등록</a>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<p class=\"chapter\">[실습3: MVC 게시판]</p>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"mvc/board?action=list\" target=\"iframe\">게시판 목록</a>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</aside>\r\n");
      out.write("\t\t\t\t<section>\r\n");
      out.write("\t\t\t\t\t<iframe name=\"iframe\" width=\"100%\" height=\"100%\"></iframe>\r\n");
      out.write("\t\t\t\t</section>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<footer>\r\n");
      out.write("\t\t\t\t덕이네\r\n");
      out.write("\t\t\t</footer>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</body>\r\n");
      out.write("\t</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
